# Generated by Django 3.1.4 on 2020-12-28 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('web_v', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='lost_find_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('dete', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
