# Generated by Django 3.1.4 on 2020-12-29 11:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_v', '0002_lost_find_topic'),
    ]

    operations = [
        migrations.CreateModel(
            name='lost_find_context',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('L_F_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_v.lost_find_topic')),
            ],
            options={
                'verbose_name_plural': 'entries',
            },
        ),
    ]
