# Generated by Django 3.1.4 on 2020-12-29 11:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_v', '0003_lost_find_context'),
    ]

    operations = [
        migrations.DeleteModel(
            name='lost_find_context',
        ),
    ]
