# Generated by Django 3.1.4 on 2020-12-29 12:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('web_v', '0007_auto_20201229_2015'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lost_find_topic',
            name='dete',
        ),
        migrations.AddField(
            model_name='lost_find_topic',
            name='date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
