# Generated by Django 3.1.4 on 2021-01-08 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_v', '0008_auto_20201229_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost_find_topic',
            old_name='date',
            new_name='Tdate',
        ),
    ]
