# Generated by Django 3.1.4 on 2021-01-08 18:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_v', '0009_auto_20210109_0245'),
    ]

    operations = [
        migrations.RenameField(
            model_name='lost_find_topic',
            old_name='Tdate',
            new_name='T_F_T_date',
        ),
    ]
