# Generated by Django 3.1.4 on 2021-01-08 19:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_v', '0012_lost_find_entry'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lost_find_entry',
            options={'verbose_name_plural': 'L_F_T_entry'},
        ),
    ]
