# Generated by Django 3.1.4 on 2021-01-08 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_v', '0014_auto_20210109_0401'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lost_find_entry',
            options={'verbose_name_plural': 'L_T_F_entries'},
        ),
    ]
