# Generated by Django 3.1.4 on 2021-01-11 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_v', '0015_auto_20210109_0412'),
    ]

    operations = [
        migrations.CreateModel(
            name='electronics_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('E_T_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='necessary_topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=300)),
                ('N_T_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='necessary_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('N_T_date', models.DateTimeField(auto_now_add=True)),
                ('N_T', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_v.necessary_topic')),
            ],
            options={
                'verbose_name_plural': 'N_F_entries',
            },
        ),
        migrations.CreateModel(
            name='electronics_entry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('E_T_date', models.DateTimeField(auto_now_add=True)),
                ('E_T', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='web_v.electronics_topic')),
            ],
            options={
                'verbose_name_plural': 'E_F_entries',
            },
        ),
    ]
